### ISSUE TITLE
Curio calc

### ISSUE THREAD

**Issue by warrri** [k-t/hafen-client#4]
Make hovering over a curio display the calculated values LP/h/slot and LP/h/MW. Both time and slot values are fixed and dont scale with quality. I can give you the list.
![untitled](https://cloud.githubusercontent.com/assets/6070525/10432026/e5fc2772-7108-11e5-8a74-cfacaedc90c1.jpg)

**Comment by k-t** [comment]
Done in 836713291fdd82bd7cd12e841525c4da3da4adda
